### PR TITLE
feat/slop-63/create-custom-rest-endpoint-slop-images

### PR DESCRIPTION
**Pull request by dani9401**
## Describe your changes
- Added a custom REST endpoint to the `keystone.ts` file using `extendExpressApp`.
- This endpoint is needed to upload images to an S3 bucket for referencing when we begin allow users to upload images as part of creating a new slop/movie. 
- This endpoint also confirms that the user who is submitting the information is an authorized/valid user.
- You will need something like Postman or Bruno to test this PR.

I have recorded a short video for anyone who is not exactly sure how to test this PR (attached below)

It's also worth mentioning that there are some things with this setup that are not ideal or as clean as I would have liked because of the time constraints. 

In the AC in Jira, it mentions an "S3 URL". This is not available right now.
You can see[ my conversation in Discord](https://discord.com/channels/1078663743568883783/1237837757460779048/1247375202917023835) with Tomer about this just last night to confirm this. 

Also, the error handling on this could use some work and is not finished. Right now Postman still shows a 200 response even when a user is not authorized to make that action (to combat this, the res.json message confirms success or fail for now).

Last, the code structure could really use a clean up, creating a "middleware" file for Multer (the library we used to upload the image file from the form data).
- Multer also needs more options setup to include things like limiting size of files, types of files,  or we need to possibly look at libraries that allow image resizing. 

## Issue ticket number and link
[Slop-63](https://tripleten-apiary.atlassian.net/jira/software/projects/SLOP/boards/2?selectedIssue=SLOP-63)

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [ ] If there are changes to custom resolvers, I have added / updated automated tests
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

https://github.com/jahorwitz/slopopedia-api/assets/126746048/b0101ee0-bef6-455f-b321-011b50032ef5

### CODE REVIEW

**Comment by bduckdev** [comment]
I'm gonna test this in 45 minutes when I get home. Monstrous PR. Nice work!

**Review by bduckdev — APPROVED** [review]
Excellent work, functions as described.

With valid userId:
image

Without valid userId:
image

**Review by ajar67 — APPROVED** [review]
works as described but I did see this error in keystone.ts file and wanted to make mention of it
error-rest-endpoint

**Review by Thatalent — APPROVED** [review]
LGTM

**Pull request merged**
